"""added columns in Topic v2

Revision ID: 1f0c817cc51a
Revises: 4d0ebb0ca383
Create Date: 2026-01-14 23:55:38.978845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f0c817cc51a'
down_revision = '4d0ebb0ca383'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=100), nullable=False))

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=100), nullable=False))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('position',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.alter_column('position',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.drop_column('full_name')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
