"""Add topic fields

Revision ID: 304b3782de83
Revises: c077a38c5a93
Create Date: 2026-01-15 00:49:26.310672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '304b3782de83'
down_revision = 'c077a38c5a93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_standard', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('max_members', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Enum('ZATWIERDZONY', 'ODRZUCONY', 'OCZEKUJACY', name='topicstatus'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('max_members')
        batch_op.drop_column('is_standard')

    # ### end Alembic commands ###
