"""added columns in Topic

Revision ID: 4d0ebb0ca383
Revises: c077a38c5a93
Create Date: 2026-01-14 23:25:15.706750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d0ebb0ca383'
down_revision = 'c077a38c5a93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum(), nullable=True))
        batch_op.add_column(sa.Column('topic_justification', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('rejection_reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.drop_column('rejection_reason')
        batch_op.drop_column('topic_justification')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
