"""Initial migration

Revision ID: a92c89a43203
Revises: 
Create Date: 2026-01-15 23:29:59.273847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a92c89a43203'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('login', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('user_type', sa.Enum('STUDENT', 'PROWADZACY', 'CZLONEK_KPK', 'KOORDYNATOR_PRZEDMIOTU', 'OPIEKUN_KIERUNKU', 'ADMINISTRATOR', name='usertype'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('declaration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('W_PRZYGOTOWANIU', 'ZLOZONA', name='status'), nullable=False),
    sa.Column('submission_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Enum('mgr_inz', 'mgr', 'dr', 'dr_inz', 'dr_hab', 'dr_hab_inz', 'prof', name='title'), nullable=False),
    sa.Column('position', sa.Enum('ASYTSTENT', 'ADIUNKT', 'PROFESOR_UCZELNI', name='position'), nullable=False),
    sa.Column('is_declaration_approved', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_table('topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('declaration_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ZATWIERDZONY', 'ODRZUCONY', 'OCZEKUJACY', name='topicstatus'), nullable=False),
    sa.Column('topic_justification', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['declaration_id'], ['declaration.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('declaration_id')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('index_number', sa.String(length=6), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('is_declaration_approved', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id'),
    sa.UniqueConstraint('index_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    op.drop_table('topic')
    op.drop_table('teacher')
    op.drop_table('declaration')
    op.drop_table('account')
    # ### end Alembic commands ###
