"""added columns v3

Revision ID: f0b228605080
Revises: 1f0c817cc51a
Create Date: 2026-01-15 00:35:21.727263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0b228605080'
down_revision = '1f0c817cc51a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=150), nullable=False))
        batch_op.drop_column('name')
        batch_op.drop_column('surname')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('full_name')

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.VARCHAR(length=100), nullable=False))

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.VARCHAR(length=100), nullable=False))

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('surname', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
